### ISSUE TITLE
PHP.net SSL connection issue

### ISSUE THREAD

**Issue by jkrehm** [fpoirotte/phpfarm#11] opened 2015-06-22 23:58 UTC
This is likely more of a php.net server issue, but in case there is something that can be changed with the `wget` request, the majority of the time I get an SSL error when phpfarm tries to download from https://www.php.net/get/php-5.6.10.tar.bz2/from/this/mirror. Only one of the four IP's that I've seen – 72.52.91.14 – work. The rest time out or throw SSL errors, e.g. `OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol Unable to establish SSL connection.`.

As this is so integral to phpfarm working correctly (unless I manually download the archive file and stick it in the bzip directory – which I have done) I figured I'd report the issue. I don't know if there's anything phpfarm can do differently – e.g. extra flags on the wget request – but I hope there is, because its usefulness is somewhat limited for me right now.

I tested using both OSX 10.10 (wget 1.16.3) and Ubuntu 14.04 (wget 1.15).

**Comment by fpoirotte** [comment] 2015-06-23 18:16
Hello, thanks for taking the time to report this issue.

It seems this is caused by commit 49a40b25aceb551ef4d270ce5beb1762303cf2f4 which assumes that PHP mirrors support SSL/TLS (the official php.net website [72.52.91.14] does). However, it seems that most of them actually do not support secure connections.

I'll try to figure a fix which does not use SSL/TLS, instead relying on the GPG signature for each release (http://php.net/gpg-keys.php). I still have to work through the details though.

**Comment by jkrehm** [comment] 2015-06-23 18:18
Awesome, thanks for the response. Let me know if I can lend a hand.

**Comment by fpoirotte** [comment] 2015-06-24 20:30
I just committed a fix for this issue. Could you please give the current code in master a try?

**Comment by fpoirotte** [comment] 2015-06-24 20:49
Err, develop, not master.

**Comment by jkrehm** [comment] 2015-06-24 21:21
I just tested the develop branch in my Ubuntu 14.04 Vagrant VM and it downloaded, checked the GPG signature, configured, and compiled without issue. I think it's a success!

**Comment by fpoirotte** [comment] 2015-06-25 19:06
Thanks, I'll close this issue for now. Please reopen it if you find any unwanted side effect.

**Closed by fpoirotte** 2015-06-25 19:06 UTC

**Comment by jkrehm** [comment] 2015-06-25 19:10
How soon will the fix make its way into master?
